
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:postgresql://localhost:5432/ayush
spring.datasource.username=postgres
spring.datasource.password=Ayush@1512
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.cookie.same-site=strict
