spring.application.name=JobApp
spring.datasource.url=jdbc:postgresql://localhost:5432/ayush
spring.datasource.username=postgres
spring.datasource.password=Ayush@1512
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect